default_opa_decal_unlit = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Opaque Decal Unlit'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = '0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = '0'
f3d_mat.combiner1.D = 'TEXEL0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = '1'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = '0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = '0'
f3d_mat.combiner2.D = 'TEXEL0'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = '1'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = False
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = True
f3d_mat.rdp_settings.g_fog = False
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_1CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = False
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_AA_ZB_OPA_SURF'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Opaque Decal'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_opa_unlit_envmap = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Opaque Unlit Environment Map'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = '0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = '0'
f3d_mat.combiner1.D = 'TEXEL0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = '1'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = '0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = '0'
f3d_mat.combiner2.D = 'TEXEL0'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = '1'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = False
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = True
f3d_mat.rdp_settings.g_fog = False
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = True
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_1CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = False
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_AA_ZB_OPA_SURF'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Opaque'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_opa_shaded_tex_fog = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Opaque Shaded Texture w/ Fog'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = 'TEXEL0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = 'SHADE'
f3d_mat.combiner1.D = '0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = '1'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = '0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = '0'
f3d_mat.combiner2.D = 'COMBINED'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = 'COMBINED'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = True
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = True
f3d_mat.rdp_settings.g_fog = True
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_2CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = True
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_FOG_SHADE_A'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Opaque'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_cutout_shaded_tex_fog = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Cutout Shaded Texture w/ Fog'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = 'TEXEL0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = 'SHADE'
f3d_mat.combiner1.D = '0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = 'TEXEL0'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = '0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = '0'
f3d_mat.combiner2.D = 'COMBINED'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = 'COMBINED'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = True
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = False
f3d_mat.rdp_settings.g_fog = True
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_2CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = True
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_FOG_SHADE_A'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_TEX_EDGE2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Cutout'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_xlu_shaded_tex_fog = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Transparent Shaded Texture w/ Fog'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = 'TEXEL0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = 'SHADE'
f3d_mat.combiner1.D = '0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = 'TEXEL0'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = '0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = '0'
f3d_mat.combiner2.D = 'COMBINED'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = 'COMBINED'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = True
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = False
f3d_mat.rdp_settings.g_fog = True
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_2CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = True
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_FOG_SHADE_A'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_XLU_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Transparent'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_opa_shaded_noise = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Opaque Shaded Noise'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = 'NOISE'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = 'SHADE'
f3d_mat.combiner1.D = '0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = '1'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = 'NOISE'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = 'SHADE'
f3d_mat.combiner2.D = '0'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = '1'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = False
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = True
f3d_mat.rdp_settings.g_fog = False
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_1CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = False
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_AA_ZB_OPA_SURF'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Opaque'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_opa_shaded_white = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Opaque Shaded White'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = '0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = '0'
f3d_mat.combiner1.D = 'SHADE'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = '1'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = '0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = '0'
f3d_mat.combiner2.D = 'SHADE'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = '1'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = False
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = True
f3d_mat.rdp_settings.g_fog = False
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_1CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = False
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_AA_ZB_OPA_SURF'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Opaque'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_opa_shaded_env_color = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Opaque Shaded Env Color'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = 'ENVIRONMENT'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = 'SHADE'
f3d_mat.combiner1.D = '0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = '1'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = 'ENVIRONMENT'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = 'SHADE'
f3d_mat.combiner2.D = '0'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = '1'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = True
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = False
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = True
f3d_mat.rdp_settings.g_fog = False
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_1CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = False
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_AA_ZB_OPA_SURF'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Opaque'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_opa_shaded_texture = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Opaque Shaded Texture'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = 'TEXEL0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = 'SHADE'
f3d_mat.combiner1.D = '0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = '1'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = 'TEXEL0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = 'SHADE'
f3d_mat.combiner2.D = '0'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = '1'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = False
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = True
f3d_mat.rdp_settings.g_fog = False
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_1CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = False
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_AA_ZB_OPA_SURF'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Opaque'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_cutout_shaded_texture = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Cutout Shaded Texture'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = 'TEXEL0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = 'SHADE'
f3d_mat.combiner1.D = '0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = 'TEXEL0'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = 'TEXEL0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = 'SHADE'
f3d_mat.combiner2.D = '0'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = 'TEXEL0'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = False
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = False
f3d_mat.rdp_settings.g_fog = False
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_1CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = False
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_AA_ZB_OPA_SURF'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Cutout'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_xlu_shaded_texture = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Transparent Unlit Texture'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = 'TEXEL0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = 'SHADE'
f3d_mat.combiner1.D = '0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = 'TEXEL0'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = 'TEXEL0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = 'SHADE'
f3d_mat.combiner2.D = '0'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = 'TEXEL0'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = False
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = False
f3d_mat.rdp_settings.g_fog = False
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_1CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = False
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_AA_ZB_OPA_SURF'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Transparent'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_opa_unlit_texture = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Opaque Unlit Texture'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = '0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = '0'
f3d_mat.combiner1.D = 'TEXEL0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = '1'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = '0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = '0'
f3d_mat.combiner2.D = 'TEXEL0'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = '1'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = False
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = True
f3d_mat.rdp_settings.g_fog = False
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_1CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = False
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_AA_ZB_OPA_SURF'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Opaque'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_cutout_unlit_texture = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Cutout Unlit Texture'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = '0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = '0'
f3d_mat.combiner1.D = 'TEXEL0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = 'TEXEL0'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = '0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = '0'
f3d_mat.combiner2.D = 'TEXEL0'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = 'TEXEL0'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = False
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = False
f3d_mat.rdp_settings.g_fog = False
f3d_mat.rdp_settings.g_lighting = True
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_1CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = False
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_AA_ZB_OPA_SURF'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Cutout'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_opa_vertex_colored_texture = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Opaque Vertex Colored Texture'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = 'TEXEL0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = 'SHADE'
f3d_mat.combiner1.D = '0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = '1'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = 'TEXEL0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = 'SHADE'
f3d_mat.combiner2.D = '0'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = '1'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = False
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = True
f3d_mat.rdp_settings.g_fog = False
f3d_mat.rdp_settings.g_lighting = False
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_1CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = False
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_AA_ZB_OPA_SURF'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Opaque'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

default_xlu_vertex_colored_texture = '''

import bpy
f3d_mat = bpy.context.material.f3d_mat
bpy.context.material.f3d_update_flag = True

f3d_mat.name = ''
f3d_mat.presetName = 'Transparent Vertex Colored Texture'
f3d_mat.combiner1.name = ''
f3d_mat.combiner1.A = 'TEXEL0'
f3d_mat.combiner1.B = '0'
f3d_mat.combiner1.C = 'SHADE'
f3d_mat.combiner1.D = '0'
f3d_mat.combiner1.A_alpha = '0'
f3d_mat.combiner1.B_alpha = '0'
f3d_mat.combiner1.C_alpha = '0'
f3d_mat.combiner1.D_alpha = 'TEXEL0'
f3d_mat.combiner2.name = ''
f3d_mat.combiner2.A = 'TEXEL0'
f3d_mat.combiner2.B = '0'
f3d_mat.combiner2.C = 'SHADE'
f3d_mat.combiner2.D = '0'
f3d_mat.combiner2.A_alpha = '0'
f3d_mat.combiner2.B_alpha = '0'
f3d_mat.combiner2.C_alpha = '0'
f3d_mat.combiner2.D_alpha = 'TEXEL0'
f3d_mat.tex0.tex_set = True
f3d_mat.tex1.tex_set = True
f3d_mat.set_prim = True
f3d_mat.tint_light = False
f3d_mat.set_env = False
f3d_mat.set_blend = False
f3d_mat.set_key = True
f3d_mat.set_k0_5 = True
f3d_mat.set_combiner = True
f3d_mat.use_default_lighting = True
f3d_mat.blend_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.prim_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.env_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_center = (1.0, 1.0, 1.0, 1.0)
f3d_mat.key_scale = (0.0, 0.0, 0.0)
f3d_mat.key_width = (0.0, 0.0, 0.0)
f3d_mat.k0 = 0.686274528503418
f3d_mat.k1 = -0.16862745583057404
f3d_mat.k2 = -0.3490196168422699
f3d_mat.k3 = 0.8705882430076599
f3d_mat.k4 = 0.4470588266849518
f3d_mat.k5 = 0.16470588743686676
f3d_mat.prim_lod_frac = 0.0
f3d_mat.prim_lod_min = 0.0
f3d_mat.default_light_color = (1.0, 1.0, 1.0, 1.0)
f3d_mat.fog_color = (0.0, 0.0, 0.0, 1.0)
f3d_mat.fog_position = (970, 1000)
f3d_mat.set_fog = False
f3d_mat.use_global_fog = True
f3d_mat.rdp_settings.name = ''
f3d_mat.rdp_settings.g_zbuffer = True
f3d_mat.rdp_settings.g_shade = True
f3d_mat.rdp_settings.g_cull_front = False
f3d_mat.rdp_settings.g_cull_back = True
f3d_mat.rdp_settings.g_fog = False
f3d_mat.rdp_settings.g_lighting = False
f3d_mat.rdp_settings.g_tex_gen = False
f3d_mat.rdp_settings.g_tex_gen_linear = False
f3d_mat.rdp_settings.g_shade_smooth = True
f3d_mat.rdp_settings.g_clipping = False
f3d_mat.rdp_settings.g_mdsft_alpha_dither = 'G_AD_NOISE'
f3d_mat.rdp_settings.g_mdsft_rgb_dither = 'G_CD_MAGICSQ'
f3d_mat.rdp_settings.g_mdsft_combkey = 'G_CK_NONE'
f3d_mat.rdp_settings.g_mdsft_textconv = 'G_TC_FILT'
f3d_mat.rdp_settings.g_mdsft_text_filt = 'G_TF_BILERP'
f3d_mat.rdp_settings.g_mdsft_textlut = 'G_TT_NONE'
f3d_mat.rdp_settings.g_mdsft_textlod = 'G_TL_TILE'
f3d_mat.rdp_settings.g_mdsft_textdetail = 'G_TD_CLAMP'
f3d_mat.rdp_settings.g_mdsft_textpersp = 'G_TP_PERSP'
f3d_mat.rdp_settings.g_mdsft_cycletype = 'G_CYC_1CYCLE'
f3d_mat.rdp_settings.g_mdsft_color_dither = 'G_CD_ENABLE'
f3d_mat.rdp_settings.g_mdsft_pipeline = 'G_PM_1PRIMITIVE'
f3d_mat.rdp_settings.g_mdsft_alpha_compare = 'G_AC_NONE'
f3d_mat.rdp_settings.g_mdsft_zsrcsel = 'G_ZS_PIXEL'
f3d_mat.rdp_settings.clip_ratio = 1
f3d_mat.rdp_settings.set_rendermode = False
f3d_mat.rdp_settings.rendermode_advanced_enabled = False
f3d_mat.rdp_settings.rendermode_preset_cycle_1 = 'G_RM_AA_ZB_OPA_SURF'
f3d_mat.rdp_settings.rendermode_preset_cycle_2 = 'G_RM_AA_ZB_OPA_SURF2'
f3d_mat.rdp_settings.aa_en = False
f3d_mat.rdp_settings.z_cmp = False
f3d_mat.rdp_settings.z_upd = False
f3d_mat.rdp_settings.im_rd = False
f3d_mat.rdp_settings.clr_on_cvg = False
f3d_mat.rdp_settings.cvg_dst = 'CVG_DST_CLAMP'
f3d_mat.rdp_settings.zmode = 'ZMODE_OPA'
f3d_mat.rdp_settings.cvg_x_alpha = False
f3d_mat.rdp_settings.alpha_cvg_sel = False
f3d_mat.rdp_settings.force_bl = False
f3d_mat.rdp_settings.blend_p1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_p2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m1 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_m2 = 'G_BL_CLR_IN'
f3d_mat.rdp_settings.blend_a1 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_a2 = 'G_BL_A_IN'
f3d_mat.rdp_settings.blend_b1 = 'G_BL_1MA'
f3d_mat.rdp_settings.blend_b2 = 'G_BL_1MA'
f3d_mat.draw_layer.gltf64 = 'Transparent'
bpy.context.material.f3d_update_flag = False
f3d_mat.env_color = f3d_mat.env_color # Force nodes update
'''

material_presets = {
	"default" : {
		"opaque_shaded_white" : default_opa_shaded_white,
		"opaque_shaded_env_color" : default_opa_shaded_env_color,
		"opaque_unlit_envmap" : default_opa_unlit_envmap,
		"opaque_unlit_texture" : default_opa_unlit_texture,
		"opaque_shaded_texture" : default_opa_shaded_texture,
		"opaque_shaded_tex_fog" : default_opa_shaded_tex_fog,
		"cutout_unlit_texture" : default_cutout_unlit_texture,
		"cutout_shaded_texture" : default_cutout_shaded_texture,
		"cutout_shaded_tex_fog" : default_cutout_shaded_tex_fog,
		"transparent_shaded_texture" : default_xlu_shaded_texture,
		"transparent_shaded_tex_fog" : default_xlu_shaded_tex_fog,
		"opaque_vertex_colored_texture" : default_opa_vertex_colored_texture,
		"transparent_vertex_colored_texture" : default_xlu_vertex_colored_texture,
		"opaque_decal_unlit" : default_opa_decal_unlit,
		"opaque_shaded_noise" : default_opa_shaded_noise,
	},
}
