CCMUXDict = {
	'COMBINED' : 	    0,
	'TEXEL0' : 		    1,
	'TEXEL1' : 		    2,
	'PRIMITIVE' : 	    3,
	'SHADE' : 		    4,
	'ENVIRONMENT' : 	5,
	'CENTER' : 		    6,
	'SCALE' : 		    6,
	'COMBINED_ALPHA' : 	7,
	'TEXEL0_ALPHA' : 	8,
	'TEXEL1_ALPHA' : 	9,
	'PRIMITIVE_ALPHA' : 10,
	'SHADE_ALPHA' : 	11,
	'ENV_ALPHA' : 	    12,
	'LOD_FRACTION' : 	13,
	'PRIM_LOD_FRAC' : 	14,
	'NOISE' : 		    7,
	'K4' : 		        7,
	'K5' : 		        15,
	'1' : 		        6,
	'0' : 		        31
}

ACMUXDict = {
	'COMBINED' : 	    0,
	'TEXEL0' : 		    1,
	'TEXEL1' : 		    2,
	'PRIMITIVE' : 	    3,
	'SHADE' : 		    4,
	'ENVIRONMENT' : 	5,
	'LOD_FRACTION' : 	0,
	'PRIM_LOD_FRAC' : 	6,
	'1' : 		        6,
	'0' : 		        7,
}
